#index:
#    path: /
#    controller: App\Controller\DefaultController::index

captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"

calendar:
  resource: "@CalendarBundle/Resources/config/routing.yaml"

